version: '2'
services:
  elk:
    image: testing-with-logging/elk
    links:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5001:5001"
      - "31311:31311"
    container_name: elk
    logging:
      options:
        max-size: "50m"
        max-file: "3"

  user_service:
    image: testing-with-logging/user
    ports:
      - "8081:8080"
    links:
      - elk
    environment:
      - LOGSTASH_ENABLED=true
      - LOGSTASH_HOST=elk
      - LOGSTASH_PORT=5001
      - LOGSTASH_APP_NAME=user
    container_name: user
    logging:
      options:
        max-size: "50m"
        max-file: "3"

  shop_service:
    image: testing-with-logging/shop
    ports:
      - "8082:8080"
    links:
      - elk
      - user_service
      - test_server
    environment:
      - LOGSTASH_ENABLED=true
      - LOGSTASH_HOST=elk
      - LOGSTASH_PORT=5001
      - LOGSTASH_APP_NAME=shop
      - USER_API_URL=http://user:8080
      - EXTERNAL_RATINGS_API_URL=http://test_server:8080/mocks/ratings
    container_name: shop
    logging:
      options:
        max-size: "50m"
        max-file: "3"

  test_server:
    image: testing-with-logging/test-server:latest
    ports:
      - "8090:8080"
    depends_on:
      - elk
    links:
      - elk
    environment:
      - LOGSTASH_ENABLED=true
      - LOGSTASH_HOST=elk
      - LOGSTASH_PORT=5001
      - LOGSTASH_APP_NAME=test_server
    container_name: test_server
    logging:
      options:
        max-size: "50m"
        max-file: "3"

  redis:
    image: testing-with-logging/redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    container_name: redis
    logging:
      options:
        max-size: "50m"
        max-file: "3"

volumes:
  redis:
    driver: local

